# Generated by Django 4.1.5 on 2023-04-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_buy_sell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buy_sell",
            name="stock_price",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="buy_sell",
            name="stock_shares",
            field=models.CharField(max_length=50),
        ),
    ]
