# Generated by Django 4.1.5 on 2023-04-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_alter_buy_sell_stock_name_alter_buy_sell_stock_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buy_sell", old_name="stock_shares", new_name="number_of_shares",
        ),
        migrations.RenameField(
            model_name="buy_sell", old_name="stock_name", new_name="stock_symbol",
        ),
    ]
