# Generated by Django 4.1.5 on 2023-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_remove_buy_sell_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=100)),
                ("number_of_shares", models.BigIntegerField()),
            ],
        ),
    ]
